# Site settings
title: Jekyll shop powered by Snipcart
email: geeks@snipcart.com
description: 
baseurl: "/eyesi.co" # the subpath of your site, e.g. /blog/
url: "http://eyesi.co" # the base hostname & protocol for your site
facebook_username: eyesieyesi
instagram_username:  eyesieyesi
api_key: YjdiNWIyOTUtZTIyMy00MWMwLTkwNDUtMzI1M2M2NTgxYjE0

# Build settings
markdown: kramdown
collections:
  products:
    output: true
